### ISSUE TITLE
 An exception occurred in driver: could not find driver 

### ISSUE THREAD

**Issue by kafkiansky** [ElisDN/demo-project-manager#2]
Здравствуйте! Использую вашу сборку, только вместо postgres хочу подключить mysql. Написал следующие docker-файлы:

php-fpm.docker
```
FROM php:7.2-fpm

RUN apt-get update && apt-get install -y libmcrypt-dev mysql-client \
    && docker-php-ext-install mcrypt pdo_mysql

WORKDIR /app
```

php-cli.docker
```
FROM php:7.2-cli

RUN apt-get update && apt-get install -y libmcrypt-dev mysql-client \
    && docker-php-ext-install mcrypt pdo_mysql pcntl

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/bin --filename=composer --quiet

ENV COMPOSER_ALLOW_SUPERUSER 1

WORKDIR /app
```

В docker-compose.yml добавил образ mysql:
```
engine-mysql:
    image: mysql:5.7
    restart: always
    environment:
      - "MYSQL_ROOT_PASSWORD=xx"
      - "MYSQL_USER=user"
      - "MYSQL_PASSWORD=xx"
      - "MYSQL_DATABASE=db"
     ports:
        - "3306:3306"
```

При попытке выполнения следующих двух команд возникает ошибка, которую указал в заголовке:

```
docker-compose exec php-fpm bash &&
php bin/console doctrine:database:create
```

Подскажите, что может быть не так?

**Comment by ElisDN** [comment]
Верните настройки в `config/packages/doctrine.yaml`:

```
doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '5.7'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci

        url: '%env(resolve:DATABASE_URL)%'
```

и в `.env`:

```
DATABASE_URL=mysql://user:xx@manager-mysql:3306/db
```
